### ISSUE TITLE
Missing xp_fastboot

### ISSUE THREAD

**Issue by CromFr** [NWNX/nwnx4#1]
According to http://www.nwnx.org/phpBB2/viewtopic.php?t=1193, xp_fastboot were on @virusman SVN server.

Does anybody have those source files?

**Comment by virusman** [comment]
It's in skywing-dev branch:
https://github.com/NWNX/nwnx4/tree/skywing-dev/src/plugins/xp_fastboot

**Comment by CromFr** [comment]
my bad, thanks ;)
